FROM public.ecr.aws/amazonlinux/amazonlinux:2023-minimal
RUN mkdir -p /tmp
COPY bountynet-bin /usr/local/bin/bountynet
COPY src/ /src/
CMD ["sh", "-c", "bountynet enclave /src --cmd true 2>&1; sleep 600"]
