#!/usr/bin/env bash
# Generate eat-pass VerificationPolicy JSON from a cvm-agent registry entry or raw measurement.
#
# Usage:
#   ./deploy/gen-eat-pass-policy.sh --measurement <hex> --out policy.json
#   ./deploy/gen-eat-pass-policy.sh --registry ../registry/8c9587c0981d7878.json --out policy.json
#   ./deploy/gen-eat-pass-policy.sh --registry ../registry/8c9587c0981d7878.json --gate azure --id uqaz1-prod --out policy.json
#
# Azure attester (--gate azure) keys on SNP launch measurement from the vTPM bundle
# (what eat-pass-gate returns as value_x after crypto verify). Prefer
# platform_measurements.snp_measurement in the registry entry when present.

set -euo pipefail

GATE="${GATE:-azure}"
POLICY_ID="${POLICY_ID:-generated-policy}"
OUT=""
MEAS=""
REGISTRY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --measurement) MEAS="$2"; shift 2 ;;
    --registry) REGISTRY="$2"; shift 2 ;;
    --gate) GATE="$2"; shift 2 ;;
    --id) POLICY_ID="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$OUT" ]]; then
  echo "missing --out" >&2
  exit 1
fi

if [[ -n "$REGISTRY" ]]; then
  if [[ ! -f "$REGISTRY" ]]; then
    echo "registry file not found: $REGISTRY" >&2
    exit 1
  fi
  MEAS="$(python3 - "$REGISTRY" <<'PY'
import json, sys
path = sys.argv[1]
with open(path) as f:
    j = json.load(f)
pm = j.get("platform_measurements") or {}
meas = pm.get("snp_measurement") or pm.get("tdx_mrtd") or pm.get("nitro_pcr0")
if not meas:
    sys.stderr.write("registry entry has no platform_measurements; use --measurement with SNP launch hex\n")
    sys.exit(1)
print(meas.strip())
PY
)"
  STATUS="$(python3 -c "import json; print(json.load(open('$REGISTRY')).get('status','recommended'))")"
  NOTES="$(python3 -c "import json; j=json.load(open('$REGISTRY')); print(j.get('notes','')[:200])")"
  REGISTRY_STATUS="$STATUS"
else
  if [[ -z "$MEAS" ]]; then
    echo "need --measurement or --registry" >&2
    exit 1
  fi
  REGISTRY_STATUS="recommended"
  NOTES="Generated by deploy/gen-eat-pass-policy.sh"
fi

case "$GATE" in
  azure) PROFILE="azure-snp-bundle" ;;
  azure-tls) PROFILE="azure-attested-tls" ;;
  uq) PROFILE="uq-eat" ;;
  android-key|android) PROFILE="android-key-attestation" ;;
  ios-app-attest|ios) PROFILE="ios-app-attest" ;;
  *) echo "unknown --gate $GATE" >&2; exit 1 ;;
esac

TRUST_NOTE="Azure CVM: MAA verifies guest quote; paravisor owns report_data. Quote proves launch measurement + guest binding, not physical location (Rezabek arXiv:2510.12469). Policy allow uses launch measurement only (Misiani SIGMETRICS 2025)."

mkdir -p "$(dirname "$OUT")"
python3 - "$OUT" "$POLICY_ID" "$PROFILE" "$MEAS" "$REGISTRY_STATUS" "$NOTES" "$TRUST_NOTE" <<'PY'
import json, sys
out, pid, profile, meas, reg_status, notes, trust = sys.argv[1:8]
doc = {
    "version": 1,
    "id": pid,
    "valid_until": "2027-01-01T00:00:00Z",
    "evidence_profile": profile,
    "class": {"name": "accepted-builds", "version": 1},
    "registry_minimum": "recommended",
    "notes": f"{trust} Registry: {notes}".strip(),
    "allow": [{
        "measurement": meas.strip().lower(),
        "registry_status": reg_status,
    }],
}
with open(out, "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
print(f"OK  wrote {out} (measurement={meas[:16]}…)")
PY
